services:
  ai_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_api
    image: ai-myapi:latest    
    environment:
      - PYTHONUNBUFFERED=1   
    expose:
      - "8080"
    volumes:
      - .:/app
    networks:
      - chatbox

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ai_api
    networks:
      - chatbox

networks:
  chatbox:
    driver: bridge
